version: '3'

services:
  app:
    image: node:12
    tty: true
    restart: always
    volumes:
      - .:/var/www/app
    working_dir: /var/www/app
    ports:
      - '3000:3000'
      - '8080:8080'
